services:
  - type: web
    name: ago-functions
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    postBuildCommand: python3 -c "import plotly, os, shutil; src=os.path.join(os.path.dirname(plotly.__file__), 'package_data', 'plotly.min.js'); dst=os.path.join(os.getcwd(), 'static', 'plotly.min.js'); os.makedirs(os.path.dirname(dst), exist_ok=True); shutil.copy2(src, dst)"
    startCommand: gunicorn -w 3 --timeout 600 -b 0.0.0.0:$PORT app:app
    healthCheckPath: /
