# config.py
"""
Global configuration constants for the portfolio function.
"""
from Functions.themes import *

REPORT_LOGO_SRC = "https://cdn.brandfetch.io/idCL5_YhIb/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1694087448850"

ANALYSIS_PAGE_URL = "https://app.alphasentra.com/ticker/[ticker]"

# Optimisation default targets
SHARPE_TARGET = 1.0
SORTINO_TARGET = 1.5
IR_TARGET = 0.5
MAX_POSITION_SIZE = 20.0
MAX_SECTOR_SIZE = 30.0
MIN_POSITION_SIZE = 0.50

# Default market data provider
DATA_PROVIDER = "yfinance"

# Candidate benchmarks for automatic selection (ordered by preference)
BENCHMARK_CANDIDATES = ["^AXJO", "^GSPC", "^STOXX50E", "BTC-USD", "^990100-USD-STRD"]

BENCHMARK_NAMES = {
    "^AXJO": "ASX 200",
    "^GSPC": "S&P 500",
    "^STOXX50E": "Euro Stoxx 50",
    "BTC-USD": "Bitcoin",
    "^990100-USD-STRD": "MSCI World",
    "ES=F": "S&P 500 Futures",
}

# AI Prompt
PORT_INTEL_REPORT_PROMPT = """gAAAAABqQjcfVVMmgWc_lHbYpOz_LBWegc_OvQ6aRh0XnflcqHZYUi5nAlQQ3LmEAuK78ZOEQXIUDU04xTsCkk11_EBz4GSR_5-Fj_mQNo_koB_mnF0c6km5eBMts6FZjzEpzunES008mRJkFb94VnAK_0swrG0NTfhAk3GQKV-C_XaeZ_USirY_3qMSH9AwVWobeL0XJGNNStpH_ouyTSocVEvZ6Oe_Xow0EqrMWdFfvtpf6vr_2O0FSIOVvMJb32hfg96Mf54JttXYgJJE9NTj21rKMlCPr-_SPxqupJzg-FZGMUh-mJ3OfscFxgTpCI8dMEBJ6K05M3V89zaiLbcB4FmYf8UAbhcowQFxsT86YjRcbSOAJUw2euI-tlG24qISx8Q8wEbiWLvGz4gJZVLkuMrQg9BciAwFFsrvn4tt4zwPEKpToyv2_5E3rxn00vDcLM0RsNquRWhnBmJoVUmoOb1WCkSjhsDK7SxZXMdSNoxU8QwjNtpZUf60_nq95DXZhXUFbiRP4OMHYvNZaJuEiA4mZK24qsDRDcgMS55uznZIf6WD3FmCWftb2UEDgbOk6e4PLAHP-vNs1Tenpe_87gQakLzORqVeXyZTLMijp4lJCpSTVBjZaFS9StuuHKLwtRziHohZREe2OMgXlQ07_Bbb8BlyDjthVYPCKaiYfl8zuW63erp6aVVtH38OvrW6nRRzioSR-SQQORYE1l9z9GhPtgd9tGYAbTwQtRgh2-8PcJb_3M4gsMLmZPDm1noQVqRoLRSPUOPLJxa4jVMoZ466C1iI_azFTKe5wZI1dFhaizI2CQf1F1PtP4EW1yx_ZFMV0Nd2tj6IG11AZ9GLQ4lpt2qBKEmCy4mc03Px6N-m1a4CZabaCt8l421cc4wiwCuxBQJbvmxN-bGPlj_R-_bfBQJrhZSbhVCuJcTd2IA9CHuYEsmxvtflvwzSKRhdWoV14sh1nitKY4ldnKMNJTMdxz9mTKT-bHOyrYSMEYgT3QYTiymMLKU_wpGjnGkND1hglKLazUfMuIgYX7D5h3tXuRFfSp2ZDj6SNDDhyoZGYDJ4gHPWNQNoHT0qJpBZLo5MjP_u67RZ7Vh-qr2J3wBHjamhhvEUk1W0RQeoyGTY3aktoSskWdsIPfBYCvKOWfYS_VYjVSeJdoBBqjmW20HCPdyp3k4viCtOgmTXwf2teFEzJ7vhH-UKZMsNz2dNEsB1hAI1MLPy2EgS96QVfzVMSvvpLM51EZ5knih2zD2EEi4jfBg948reIW90EPy-U8GeyVM2otERKBy0Hds4ttL1-GQl_h4zuzfHF_13taMrRUOs4C5kkCCaIonPxyMxrUROYBZRtJPdnxjP5jzu9KRQUBZalQX4AoL4F9xHCTP7owQ5aau07R7eGsaAn4M8PJw8oEGU-7xHw8Pe4IOsFcZjcrqUMFJb0X2hph7qa7YJqOvDJqzIllXCZKtopcvngZ92LYSNWm0v1Rfqb5bDn1SdL8nk7N4PMA6qKUxl4II-6hlGlD4VdKsGnuNzbaxZkUZxlITFVmz_FKvemz3uXOp5K0pZsgUGdmsfDvPRtR-54tJO6lLA6pvRV-FrUKqCCuPmzz-MEkyW8oZf4XpToVzel_bLv4JaFIc6o43HtpVwfNB97Aiq5Co2q5ABTu8rXK4NGdER3sk5S89UlCAP0qz6cm1JVSH321z27vE8dGhGrDNzkbKrFGbdtdVIdM-bJYzrZI6eC7BnEAri6C4A1IOsfepmySOmiZJtNfSRETNub5ISDisyvQQK3ehYPoRKPticr71OvNpf0VTdLaIk8StcyZEVeUs-6b7vMC_eVxB41wXoUCF1UhvRivCt2Kxcy1OhjGq4f7EzJBkeFhqrCNYLOmD0PPKlM_RD8DFmX8esEx9Z3UYvlAv-qL8RneT_Lmyj7IEkQ47DgwqBQjYBeTEZu4PjuFaFHnKejHyGqk-Jdfj8MXDOLb-kjp2gSH9tIqWpNpJCKR9_lPw1WW9VFOVua3GdtvCvJKdkP6yZ-j8KiJISndP3eSb5aYVQnDvYZkuQMee9zZ8i6-ME80UWZz5FkA_GRnpebfcaujM204XBJ8Db0nS1r8uXY6nH7WTJ0B5r0ALC9oXoZhYPIYDK38hEMpqgNXY0Jt41WztkR6o0dht6MUdqda8FC9U0aBbKcUTnwcISicBFRzlr2ybmiCar2RaI30-6oRjn9qmmIPbMKeY2afU4CwQKK1Zy9F2-Z_sCAn9Rh1Tv8uSZfBaq0_X60BR7Jc3pPZ-WI8GWhgXInbDuvSUFiLWh2B0I4qFiJ_yfgCefNVPjcuZSo1KNxT7-ShCxm29s381_kVrqCQJde5_2JsoxJ20VpoXXEQjGaYJXPAAIB0vSL4yJNKB7ktuUuptxehXebtUWLU7r7Wvzw0GUQ9qhhcsxVBkk9rLTU_3D0fdFukgIc1iI3HwGKkndaUL7Jg91AQLxpOkaWyv_eTvJTv8PvuVsoi_2vrPlMIbQhDvjNR8l7qJCkbFYF_C-zaZoM2r9NxV4fnstbYIs1ysFPcCW2FpeVoZh6pejq61UH2det5nw23eCTjqCylPyEXMibZu24gTNNrsxOt7Mabe_2SeRMwAOBr2Lc1JYWdmMJ_5atuKZrhZplgv069N4vXohX0NPavRX7_YCtfgVdVq5JVP0C1AHYTsKk1oPal4TUVCkyU2kSrBC6J34wZCzeQ2gtZw1mdoPiDm1QJVnxEP_mQoQOxVnlMddTR8hK8QijJ6j90GtCn6_wH7fma9p-z0HvLtWjBMJJ6XEPH7Cq1VP3bXqIVk19anXN8xCf93YMkh2ovmsuTYU8KpxpvOfi7bnME35hs13BbTK6MEkyIjKdsXket3D_rZTADcw9IicjjsKVxVrtpMFL1W6wQ06evN4XFLrbacKQjZTldRhF_1YCXREVMz4sv8Tn5tb4YTxpOVckHojOweLJqU8QJGgl7Dlj0w472X_BlFmqJxvZZ0EUKFjn3MOqEjTl5RUWRlYpoAkg_TumBE3-n5CR6Ng8YR9GJTGjpnDZbq6gIs9wW6QV0fbHe4sRksuE9EC55mSLZljij_JYmNVc8DSIKl5t1Ff593KsRLYn-xjly2bw1BGq_P3Dk4qaBYnd7Z7Vf8g56y94Dj8B7EbL24kkXyl-iX2NtvEJnFjcuARuiOupRhYUXJwt3h5__rRGaFhvCQtQdU8JTdzZrrhvk31TJI0K1skWAHqiwCsp7T8qMCCh4b8yUyq8GCBsOltFtDvguJHtDIDArZ_nypVFVPSemXdpqrxjAc18nGLs61PQYfLfidacg_Z0T5G9OCFLTFzZX6vqX8xy_5qXT6vLzkEh61mGiu0Fq-ZN66EJB-A5hvL6atrwqIDmwuG5gBhTtVytAqwYGyvUbL3s4ZeXfu85BBjFbSLic5N15dVcYG08goq8sWX5Nan-kVeNnoW9_H3Dp3FXLq9m8DC93V3c07T4ku6m6o8xIAMxO6N_s16GHR-JzvG96Zouh-oKGV6u_1cl2MIM-rBHUuqcAs9qlyKlsDBYFv8hTjnWOo7sei8byo1q1YVcj927cmJTYhYRbt2GyfuqiHxh4zgbSA1Je0tgkS8VNOv_VP-pJuBIAEiGZ09i1RYNAIgZ9RnZxt0gW4rZqTwh3iPxVA3tnC6bAz2wU9k7YLd1qQ5uFsemBzWI1mTLeoXt69-oxwIluXKWvoFOi8StEuKtGHlKBEtd-a-MNo5CDxBYwpppDX5oEIdylwbku5aLZ6_FDS_rOVwsReGh3pzhwef3RmT4e82DrJLS02qWJCq204jZmCXYMfTcHcsJsUT9rF0TYviou8Xppa3IPZaknU6OsEe6tbgrZNZICbU9Z4wDjXp7Bg8nNmPRu8vqFXukjM1cDJ_YGWfnSEhNHKKv5eDn-I0vww168myTnNyDQuanghR-EsHG_X6rAHwra51gEzuj9VNOytMj6JFINf3ZtYRpSvc1eLxfXTfAUuzWBcQI6xFVXHliNhLvtvdyMtiCQAiL7FTheGM7fEYBEhuN5yiNrLz2QzYCDe1yLumoGZM44G4rjpv8uCmssefQ1sScyQkt0NF2tjjU5qQevbTyGkRIQoLt6TB7CLtzeXmO70xt3gAKNvlEhXKBrv2k6NN8_kx5iV7zmXqYeQN9x6pKEMzdNzv5Fxc-8BOT_dP8cAtD9TNCkz5XkmqJY9C3-jCymVSDU5bTeNsNnqM-qiUWeOjvcSzrz4erij1U-1PXDPxH94sR01HSWYCqeClM49NTNcbB4gI5r5hJfWtx3UbMi2c2WQ4WVP6AWk4QvIOSAr88KIe5JxPMc88_EuxWqPDl9OGrBnv3kR1fxH2tOI1oI3sxYXzBR1qg4IehBiyF29Vn1etExs9m-W1wvutxp_D2rstkiyi_JduMZxfFMvWZyZbs0avf5Pb7sdt1RdpZJvo4vXbKv7jw2CPdNpRq6FfWg3MGs8iWNCFD1uz6V8XZ99Xny-P2_HTq4MyHXzT-xmhC-dtacJuh7xqiFsqwWtA-cMQ2Ex2PxOcuBM4KiSo4Tb8OKRvBu-XuaWMZK7GVqoI9KspxeEJB7k_TzH5FRSZBzwAMQlFBELAX-Cj_g-PabkB4enMJ2BZOD6kHUxyco3pqprIjFx_Lu34OOqaVDVHsb7JP-wSQTyBhGQ2TPJb5VbYoRQeP3lNMAGpmN1Iybp4UCrA9wR2F7KbACUQKtB_b9GWF-E3E2vwpa4uPF3NkddrgeAycLq5B-Wa7VXRNyAXaio2naaAqHD8SXTRNpKcypnocPoPpDZh8aIASOAd2Xf3Wrz_CiyKxtez6pUi__c6c2A1PCoakCaW1ePa8ZrpEGA="""

def get_benchmark_name(ticker):
    return BENCHMARK_NAMES.get(ticker, ticker)

#Optimistion default capital
DEFAULT_CAPITAL = 10000.0


# ============================================================
# UI Colors and Design Tokens
# ============================================================
LIGHT_ELEMENT = _NEUTRAL_0

# Text
TEXT_PRIMARY = _TEXT_PRIMARY
TEXT_SECONDARY = _TEXT_SECONDARY
TEXT_MUTED = _TEXT_MUTED
TEXT_ON_DARK = LIGHT_ELEMENT
TEXT_ON_YELLOW = _TEXT_HEADING
TEXT_TAB_HOVER = _TEXT_SECONDARY
TAB_ACTIVE = _BRAND_PRIMARY
TEXT_ERROR = _SEMANTIC_NEGATIVE_STRONG
TEXT_MARKER_DARK = _NEUTRAL_1000
TEXT_LABEL_GAUGE = _TEXT_MUTED
TEXT_HEADING_H2 = _TEXT_HEADING_H2
TEXT_HEADING_H3 = _TEXT_HEADING_H3

# Surfaces
BG_ROW_HEADER = _BG_ROW_HEADER
BG_ROW_HEADER_ALT = _BG_SUBTLE
BG_ROW_ALT = _BG_ROW_ALT_2
BG_ROW_ALT_ALT = _BG_ROW_ALT_2
BG_ROW_HOVER = _BG_ROW_HOVER
BG_CHART = _BG_CHART
BG_TAB_INACTIVE = _NEUTRAL_SURFACE
BG_TAB_HOVER = _HOVER_SURFACE
BG_ACTIVE_YELLOW = _COMMENTARY_BG
BG_OPT_CARD = _NEUTRAL_0
BG_SHOCK_KNOWLEDGE = _BG_SUBTLE
NEUTRAL_SURFACE = _NEUTRAL_SURFACE
WHITE_ELEMENT = _WHITE_ELEMENT

# Borders
BORDER_LIGHT = _BORDER_DEFAULT
BORDER_PANEL = _BORDER_DEFAULT
BORDER_CHART_HEADER = _BORDER_DEFAULT
BORDER_INFO = _SEMANTIC_NEGATIVE

SUCCESS_DARK = _SEMANTIC_POSITIVE
DANGER_DARK = _SEMANTIC_NEGATIVE
WARNING_ACCENT = _SEMANTIC_WARNING
ERR_DARK = _SEMANTIC_NEGATIVE_STRONG

# Gauges / Sliders
GAUGE_TRACK_BG = _NEUTRAL_SURFACE

# Chart series
CHART_GRID = _GRID_LINE

# Drawdown risk bar
DD_RISK_BAR_LOW = _SEMANTIC_NEGATIVE
DD_RISK_BAR_MEDIUM = _SEMANTIC_WARNING
DD_RISK_BAR_HIGH = _SEMANTIC_POSITIVE
DD_RISK_BAR_BORDER = _TEXT_PRIMARY
DD_RISK_MARKER = _NEUTRAL_1000
DD_RISK_LABEL = _TEXT_MUTED

# Correlation percentile bar
CORR_PERCENTILE_20 = _SEMANTIC_NEGATIVE
CORR_PERCENTILE_40 = _SEMANTIC_WARNING
CORR_PERCENTILE_60 = _SEMANTIC_POSITIVE
CORR_PERCENTILE_80 = _SEMANTIC_WARNING
CORR_PERCENTILE_100 = _SEMANTIC_NEGATIVE
CORR_PERCENTILE_MARKER = _NEUTRAL_1000
CORR_PERCENTILE_BORDER = _TEXT_PRIMARY

# Term curve
TERM_CARD_BORDER = _NEUTRAL_SURFACE
TERM_CARD_BAR =_BRAND_PRIMARY

# Monte Carlo card backgrounds
MC_CARD_GREEN_BORDER = _SEMANTIC_POSITIVE
MC_CARD_RED_BORDER = _SEMANTIC_NEGATIVE
MC_CARD_ORANGE_BORDER = _SEMANTIC_WARNING
MC_CARD_GRAY_BORDER = _SEMANTIC_NEUTRAL

# Stability and Regime indicator colors
STABILITY_MEDIUM = _SEMANTIC_WARNING

# Alerts / Momentum / Bias colors
ALERT_CAUTION_BG = _SEMANTIC_WARNING

# Performance pills
PILL_POSITIVE_TEXT = _SEMANTIC_POSITIVE
PILL_NEGATIVE_TEXT = _SEMANTIC_NEGATIVE
PILL_NEUTRAL_TEXT = _TEXT_MUTED

PRIMARY_TEXT = _TEXT_PRIMARY
HEADING_TEXT = _TEXT_HEADING
HEADING_TEXT_H2 = TEXT_HEADING_H2
HEADING_TEXT_H3 = TEXT_HEADING_H3
ACCENT_THEME = _BRAND_PRIMARY
SUCCESS_INDICATOR = _SEMANTIC_POSITIVE
DANGER_INDICATOR = _SEMANTIC_NEGATIVE
SUCCESS_TEXT = _SEMANTIC_POSITIVE
DANGER_TEXT = _SEMANTIC_NEGATIVE
NEUTRAL_BG = _NEUTRAL_SURFACE
NEUTRAL_TEXT = _TEXT_SECONDARY
NEUTRAL_GRAY = _SEMANTIC_NEUTRAL
BG_MAIN = _BG_DEFAULT
BORDER_THEME = _BORDER_DEFAULT
CHART_TEXT = _TEXT_MUTED
CHART_LINE_CAPITAL_GAIN = _NEUTRAL_1000
CHART_LINE_SINCE_INCEPTION = _SEMANTIC_WARNING
CHART_BENCHMARK_MARKER = _TEXT_PRIMARY

# Buttons
BG_BUTTON_PRIMARY = _TEXT_HEADING
BG_BUTTON_PRIMARY_HOVER = _SEMANTIC_NEUTRAL_HOVER
BG_BUTTON_SECONDARY = _SEMANTIC_NEUTRAL
BG_BUTTON_SECONDARY_HOVER = _SEMANTIC_NEUTRAL_STRONG
BG_BUTTON_DANGER = _SEMANTIC_NEGATIVE
BG_BUTTON_DANGER_HOVER = _SEMANTIC_NEGATIVE_STRONG
BG_BUTTON_NEUTRAL = _NEUTRAL_SURFACE
BG_BUTTON_NEUTRAL_HOVER = _HOVER_SURFACE
BUTTON_TEXT = _NEUTRAL_0

# ============================================================
# Correlation heatmap colors (charts.py)
# ============================================================
HEATMAP_NEGATIVE_CELL = _SEMANTIC_POSITIVE
HEATMAP_NEUTRAL_CELL = _NEUTRAL_0
HEATMAP_POSITIVE_CELL = _SEMANTIC_NEGATIVE
HEATMAP_DIAGONAL_CELL = _TEXT_MUTED

# Correlation distribution chart colors (correlation/charts.py)
CORR_DIST_BAR_FILL = _SEMANTIC_NEUTRAL
CORR_DIST_BAR_EDGE = _NEUTRAL_1000
CORR_DIST_MARKER_LINE = _SEMANTIC_NEGATIVE
CORR_DIST_BG = _NEUTRAL_0

# Correlation chart color helpers (correlation/charts.py)
CORR_COLOR_STRONG_POSITIVE = _SEMANTIC_POSITIVE
CORR_COLOR_MODERATE = _SEMANTIC_WARNING
CORR_COLOR_WEAK_POSITIVE = _SEMANTIC_NEUTRAL
CORR_COLOR_NEGATIVE = _SEMANTIC_NEGATIVE
CORR_COLOR_NA = _SEMANTIC_NEUTRAL

# Correlation percentile bar colors (correlation/charts.py)
CORR_PERCENTILE_EXTREME = _SEMANTIC_NEGATIVE
CORR_PERCENTILE_SOMEWHAT_EXTREME = _SEMANTIC_WARNING
CORR_PERCENTILE_NORMAL = _SEMANTIC_POSITIVE

# Correlation volatility bar colors (correlation/charts.py)
CORR_VOL_HIGH = _SEMANTIC_NEGATIVE
CORR_VOL_MODERATE = _SEMANTIC_WARNING
CORR_VOL_LOW = _SEMANTIC_POSITIVE


# ============================================================
# Overview attention table colors (overview/commentary.py)
# ============================================================
ATTENTION_TABLE_HEADER_BORDER = _BORDER_DEFAULT
ATTENTION_TABLE_CELL_BORDER = _BORDER_DEFAULT
NEGATIVE_RETURN_CELL_BG = _SEMANTIC_NEGATIVE
POSITIVE_RETURN_CELL_BG = _SEMANTIC_POSITIVE
ZERO_RETURN_CELL_BG = _BG_ROW_ALT_2
NONZERO_RETURN_CELL_TEXT = _NEUTRAL_0
ZERO_RETURN_CELL_TEXT = _TEXT_MUTED
ATTENTION_TABLE_HEADER_BG = _BG_SUBTLE
ATTENTION_TABLE_HEADER_ROW_BORDER = _BORDER_DEFAULT
TABLE_PERIOD_LABEL_TEXT = _TEXT_PRIMARY
METRIC_CARD_LABEL_TEXT = _TEXT_PRIMARY
POSITIVE_RETURN_CARD = _SEMANTIC_POSITIVE
NEGATIVE_RETURN_CARD = _SEMANTIC_NEGATIVE
UNDEFINED_METRIC_CARD = _SEMANTIC_NEUTRAL

# ============================================================
# Overview performance chart colors (overview/charts.py)
# ============================================================
PERF_BAR_POSITIVE = _SEMANTIC_POSITIVE
PERF_BAR_NEGATIVE = _SEMANTIC_NEGATIVE
PERF_ACTIVE_BUTTON_BG = _TEXT_HEADING
PERF_INACTIVE_BUTTON_BG = _SEMANTIC_NEUTRAL
DIV_YIELD_CARD_BORDER = _BRAND_PRIMARY
DIV_YIELD_CARD_TEXT = _BRAND_PRIMARY
METRIC_CARD_BORDER_SCALE = _TEXT_MUTED
BAR_OUTLINE = _TEXT_PRIMARY
BAR_VALUE_LABEL_TEXT = _TEXT_PRIMARY

# ============================================================
# Holdings table renderer colors (holdings/renderer.py)
# ============================================================
HOLDINGS_CAUTION_ALERT_BG = _SEMANTIC_NEGATIVE
HOLDINGS_ATTENTION_ALERT_BG = _SEMANTIC_WARNING
HOLDINGS_MONITOR_ALERT_BG = _SEMANTIC_POSITIVE
HOLDINGS_BULL_MOMENTUM_BG = _SEMANTIC_POSITIVE
HOLDINGS_BEAR_MOMENTUM_BG = _SEMANTIC_NEGATIVE
HOLDINGS_NEUTRAL_MOMENTUM_BG = _SEMANTIC_NEUTRAL
ZSCORE_OVERSOLD = _SEMANTIC_NEGATIVE
ZSCORE_OVERBOUGHT = _SEMANTIC_POSITIVE
ZSCORE_NEUTRAL = _SEMANTIC_NEUTRAL
UPSIDE_PRICE_TEXT = _SEMANTIC_POSITIVE
DOWNSIDE_PRICE_TEXT = _SEMANTIC_NEGATIVE
NEUTRAL_PRICE_TEXT = _SEMANTIC_NEUTRAL
NO_PRICE_COLOR = _TEXT_PRIMARY
TREND_ACCEL_BAR = _SEMANTIC_POSITIVE
TREND_DECEL_BAR = _SEMANTIC_NEGATIVE
TREND_NEUTRAL_BAR = _SEMANTIC_NEUTRAL
TREND_ACCEL_TEXT = _SEMANTIC_POSITIVE
TREND_DECEL_TEXT = _SEMANTIC_NEGATIVE
TREND_NEUTRAL_TEXT = _SEMANTIC_NEUTRAL
RSI_OVERSOLD_BG = _SEMANTIC_POSITIVE
RSI_OVERBOUGHT_BG = _SEMANTIC_NEGATIVE
HOLDINGS_EXPORT_BG = _TEXT_HEADING
HOLDINGS_TOOLTIP_BG = _TEXT_PRIMARY
HOLDINGS_HEADER_BG = _BG_ROW_HEADER
HOLDINGS_HEADER_TEXT = _TEXT_SECONDARY
HOLDINGS_CELL_BORDER = _BORDER_DEFAULT
HOLDINGS_ROW_ALT = _BG_ROW_ALT_2
HOLDINGS_HEADER_HOVER = _NEUTRAL_SURFACE
HOLDINGS_ROW_HOVER = _BG_ROW_HOVER
HOLDINGS_SORT_ARROW = _BRAND_PRIMARY
HOLDINGS_SORT_ARROW_TEXT = _TEXT_HEADING
HOLDINGS_STDEV_LABEL = _TEXT_MUTED

# Holdings commentary alert table (commentary.py)
HOLDINGS_COMMENTARY_ALERT_CAUTION = _SEMANTIC_NEGATIVE
HOLDINGS_COMMENTARY_ALERT_ATTENTION = _SEMANTIC_WARNING
HOLDINGS_COMMENTARY_ALERT_MONITOR = _SEMANTIC_POSITIVE

# ============================================================
# History chart colors (history/charts.py)
# ============================================================
EMPTY_PLACEHOLDER_TEXT = _TEXT_MUTED
TRADE_WINRATE_GOOD = _SEMANTIC_POSITIVE
TRADE_WINRATE_MODERATE = _SEMANTIC_WARNING
TRADE_WINRATE_BAD = _SEMANTIC_NEGATIVE
TRADE_RR_NEUTRAL = _SEMANTIC_NEUTRAL
TRADE_RR_GOOD = _SEMANTIC_POSITIVE
TRADE_RR_MODERATE = _SEMANTIC_WARNING
TRADE_RR_BAD = _SEMANTIC_NEGATIVE
TRADE_EXPECTANCY_GOOD = _SEMANTIC_POSITIVE
TRADE_EXPECTANCY_BAD = _SEMANTIC_NEGATIVE
TRADE_EXPECTANCY_MODERATE = _SEMANTIC_WARNING
TRADE_PF_NEUTRAL = _SEMANTIC_NEUTRAL
TRADE_PF_GOOD = _SEMANTIC_POSITIVE
TRADE_PF_MODERATE = _SEMANTIC_WARNING
TRADE_PF_BAD = _SEMANTIC_NEGATIVE
TRADE_LOSS_BAR = _SEMANTIC_NEGATIVE
TRADE_BAR_OUTLINE = _TEXT_PRIMARY
TRADE_BAR_LABEL_TEXT = _TEXT_PRIMARY
LOSS_TRADE_PIE = _HOVER_SURFACE
PIE_SLICE_BORDER = _WHITE_ELEMENT
WIN_PCT_ANNOTATION = _TEXT_MUTED

# ============================================================
# Efficiency chart colors (efficiency/charts.py)
# ============================================================
EFFICIENCY_LABEL_TEXT = _SEMANTIC_NEUTRAL_STRONG
EFFICIENCY_BETA_CARD = _BRAND_PRIMARY
EFFICIENCY_POSITIVE_CARD = _SEMANTIC_POSITIVE
EFFICIENCY_NEGATIVE_CARD = _SEMANTIC_NEGATIVE
EFFICIENCY_NEUTRAL_CARD = _SEMANTIC_NEUTRAL

# ============================================================
# Risks chart colors (risks/charts.py)
# ============================================================
RISK_NA_COLOR = _SEMANTIC_NEUTRAL
RISK_STRESS_LINE = _SEMANTIC_NEGATIVE
BENCHMARK_LINE = _TEXT_PRIMARY
RISK_DRAWDOWN_LOW = _SEMANTIC_POSITIVE
RISK_DRAWDOWN_MODERATE = _SEMANTIC_WARNING
RISK_DRAWDOWN_HIGH = _SEMANTIC_NEGATIVE
RISK_VAR_LOW = _SEMANTIC_POSITIVE
RISK_VAR_MODERATE = _SEMANTIC_WARNING
RISK_VAR_HIGH = _SEMANTIC_NEGATIVE
RISK_BETA_LOW = _SEMANTIC_POSITIVE
RISK_BETA_MARKET = _SEMANTIC_WARNING
RISK_BETA_MODERATE = _SEMANTIC_NEGATIVE
RISK_BETA_HIGH = _SEMANTIC_NEGATIVE_STRONG
VAR_CHART_MAIN_BAR = _TEXT_HEADING
VAR_CHART_TAIL_BAR = _SEMANTIC_NEGATIVE
VAR_CHART_THRESHOLD = _BRAND_PRIMARY
ES_BRACKET_LINE = _BRAND_PRIMARY

# ============================================================
# Efficiency 3D chart colors (efficiency/charts.py)
# ============================================================
EFFICIENCY_3D_GRID = _HOVER_SURFACE
EFFICIENCY_3D_ZEROLINE = _SEMANTIC_NEUTRAL
EFFICIENCY_3D_BUTTON_ACTIVE = _TEXT_HEADING
EFFICIENCY_3D_BUTTON_INACTIVE = _SEMANTIC_NEUTRAL
EFFICIENCY_SHARPE_LINE = _EFFICIENCY_SHARPE_LINE
EFFICIENCY_SORTINO_LINE = _EFFICIENCY_SORTINO_LINE
EFFICIENCY_IR_LINE = _EFFICIENCY_IR_LINE

# ============================================================
# Monte Carlo chart colors (monte_carlo/charts.py)
# ============================================================
MC_GRID = _GRID_LINE
MC_MEAN_PATH = _TEXT_PRIMARY
MC_BG = _BG_CHART
MC_POSITIVE = _SEMANTIC_POSITIVE
MC_NEGATIVE = _SEMANTIC_NEGATIVE
MC_NEUTRAL = _SEMANTIC_NEUTRAL
MC_DRAWDOWN_LOW = _SEMANTIC_POSITIVE
MC_DRAWDOWN_MODERATE = _SEMANTIC_WARNING
MC_DRAWDOWN_HIGH = _SEMANTIC_NEGATIVE

# ============================================================
# Optimisation renderer colors (optimisation/renderer.py)
# ============================================================
# Optimisation strategy constants
OPTIMISATION_CURRENT_STRATEGY = _SEMANTIC_NEUTRAL
OPTIMISATION_SHARPE_STRATEGY = _BRAND_PRIMARY
OPTIMISATION_SORTINO_STRATEGY = _SEMANTIC_POSITIVE_LIGHT
OPTIMISATION_DRAWDOWN_STRATEGY = _SEMANTIC_NEGATIVE
EFFICIENCY_SCATTER_MARKER = _BRAND_PRIMARY
EFFICIENCY_SCATTER_LINE = _SEMANTIC_NEUTRAL_HOVER
EFFICIENCY_LABEL_FONT = _TEXT_MUTED
EFFICIENCY_GRID_LINE = _GRID_LINE
EFFICIENCY_BOX_MARKER = _SEMANTIC_POSITIVE_LIGHT
EFFICIENCY_BOX_LINE = _SEMANTIC_POSITIVE

BREAKDOWN_GRID_COLOR = _GRID_LINE
BREAKDOWN_LINE_COLOR = _GRID_LINE
BREAKDOWN_NEUTRAL_ORANGE = _SEMANTIC_WARNING
BREAKDOWN_POSITIVE_GREEN = _SEMANTIC_POSITIVE
BREAKDOWN_NEGATIVE_RED = _SEMANTIC_NEGATIVE
BREAKDOWN_NEUTRAL_BLUE = _BRAND_PRIMARY

# ============================================================
# Module Visibility Toggles
# ============================================================
ENABLED_MODULES = {
    "overview": True,
    "portfolio": True,
    "stats": True,
    "holdings": True,
    "breakdown": True,
    "correlation": True,
    "monte_carlo": True,
    "risks": True,
    "efficiency": True,
    "optimisation": True,
    "history": True,
    "intel": True,
}
