# config.py
"""
Global configuration constants for the portfolio function.
"""
from Functions.themes import *

REPORT_LOGO_SRC = "https://cdn.brandfetch.io/idCL5_YhIb/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1694087448850"

ANALYSIS_PAGE_URL = "https://app.alphasentra.com/ticker/[ticker]"

# Optimisation default targets
MAX_POSITION_SIZE = 30.0
MAX_SHORT_SIZE = 30.0
MIN_POSITION_SIZE = 0.50
OPT_LONG_SHORT = False
OPT_GROSS_EXPOSURE = 2.0

# Default market data provider
DATA_PROVIDER = "yfinance"

# Candidate benchmarks for automatic selection (ordered by preference)
BENCHMARK_CANDIDATES = ["^AXJO", "^GSPC", "^STOXX50E", "^FTSE", "BTC-USD", "^990100-USD-STRD"]

BENCHMARK_NAMES = {
    "^AXJO": "ASX 200",
    "^GSPC": "S&P 500",
    "^STOXX50E": "Euro Stoxx 50",
    "^FTSE": "Footsie",
    "BTC-USD": "Bitcoin",
    "^990100-USD-STRD": "MSCI World",
    "ES=F": "S&P 500 Futures",
}

MARKET_SUFFIX_MAP = {
    ".AX": "AU",
    ".ASX": "AU",
    ".US": "US",
    ".DE": "EU",
    ".F": "EU",
    ".PA": "EU",
    ".MI": "EU",
    ".L": "UK",
}

CRYPTO_PREFIXES = ("BTC", "ETH", "BNB", "USDT", "SOL", "XRP")

MARKET_DEFAULT_BENCHMARK = {
    "AU": "^AXJO",
    "US": "^GSPC",
    "EU": "^STOXX50E",
    "UK": "^FTSE",
    "CRYPTO": "BTC-USD",
    "OTHER": "^GSPC",
}

# AI Prompt
PORT_INTEL_REPORT_PROMPT = """gAAAAABqRJVnmqKve0TluDvRbhw6LYaqPawqgzMTT4-1cCrWVq1dC5nIapfCcWsNd6s5rZZ1C-PsjqOvUIopaZjL3kpWtv6L7MKJlz28vFhcQ_9EUQn7B5tuE2D52yeEw6WCmNg6a2CRPSwscg06Qhw3ia-238ylgKlODMISGh57KqCS86Az1WvyZM_dltQrtmoXl4_Quwl3QXgEveZ-HCaY8ZuOfEXSlHkedK0Yks3WpKrFVq6uzXovfFj521C071mLOFyKopK_t4hmKAoAiKcE7uiBT763XbB3lb7vbg2y8xH3dgmVjm1ClG6D3sMxlDpHx3_X_tpMTOwiBcGCB7eocjFOL8eiMgM8cT-GieIGIPtS-551IED6krTvIZVIYbN6n7yWFL8GNRSWFXEMJjixbe4Likq3T-LQcy4uQ-_ZpYc9lps-F_ooPwdEZfoU7Kr8aMY4kEZTwFn8BFismqjy-_MDQA9qBRuERfWGT8JKm9uneBd73aKqRLosgzaQOyns6nV4tOaXrZp2v51kvQk58_hfOSyCaojfdqTKzYPoz2KnGFDuK33ggFIfiCXmcgqDGr6o7bvc9A5WdS9xrQkdnYDHWD0FbZbXmQaAit6wE8I6DRB65o7a4YEayQsSA1jcJdYbrMJxJ8-qzjowiGR3SHxKVI3THfpk1zIAMpVU3kfSvXHYWPcxF3nP4Vt5r1bRsATrq_Zwe2BD7JbDmAA1Joy2AOSMLbbImlm7QJwXSYuwgBjyob9BGdkFZzMEMFJEeJCqqkysYBCHyBtd04IUSivp5rCsIBFRhIuyMwOUc6Gr8yqrFXjWgm8_CZFtMoF1m9ukvWSdxrF_1sBoUDwRAN1M5ULYv4-y2EZczt0_OBB1484Me_-976bjMt1pBgzfS5mOK6WYOTm1BVsPvaS1Yy5Rtoo1mmlcvOqM5AjTekyl6WrqnzeyT05ji2D-XViqXjTsEAdu24tCURctZ1w-Y8worZpaZC1GDoGE-SjreD7for5KmF5YNs7QMupeVCypM_6cNNtzCo8d9uCMAQnh1RFeNZpMfCfj4Qv7J31O566i1ppsQUF8ShQWskI3MfRo9avBVCypgl_IncgnyX9cjHjLCpBHq7Usdpa6yBiJ4wD9MS4plBawGkPi2jaSrsSIbyYKQBsK-B1c2EjEY-_B8SnKUulLo1iNvfQWUYBDuHI3ibyTJcM6YL_ypwT78NHIFXAhPlwDL19YrqFY-IVxAMUOLbPKgULT_P2LTfb1ZFExpQRypORileUW9pZhbI40ecLJP3orjBB6346jjf_jemQwFc9jzgcjB2ffyPZMjicjzuzmYAhpf4enMJSqmQAHZV2wTmnZ5FE_aid2ISLrZT1PSTLTPAE-MnY6LVHI0HY9M4N_ikokeYAlOlFpSqHdFjGDZfnmN7gpOxjIT7emaPzBh_OWi05tZelCAZtE_x45UeG009T9L5XEBRKBfHqEtDrPfDv5A_E_l6_MAu5Vf-4Tx0GRPq5C0okKABI5Hy_a1q3Ne5tIPQSvUWtdbEocAX1dv7Fr3CiRFj4-NN_QQturPKxb4fvO15aiJmi1gyRhyh9tidEtYaJtFPXdbceYEGTmW25rJGPeKIig13ko593P5Lke_qKtYFeIdBhjVZ22E6x8-iA2uygmBBYJhFZSuMV6BCC_W9BQpeP7bwWdFof9MrFrMAqq32LlRbH2A1JiJVKKacxey5XlRuFwMT0xhgQUdvDl4m6ZdfQMsjtk1464pzXc3r4vnfhEuSCPKc6KGtfrCvRILo2UqYSnfMKEm8bJNeNDOj9pdp9KV6XjoulNOFUkNA7lKfrZzMnLD0-TW0kG9Z55dub7SRzwgloA6jwXocdCrirbceWteUriw3O-iKoKGZYSNP8qf6ssNsTjwGybrNlYZ50nmu3Bg_MxpAhXCZLEpY6U-h2rVBhzwKHnLAf9aL_mJs407PMpSEsD1YTOgHKpQOqth_YFRA1oKm0NUkFrzeNbQvlJW5YszP3BIqGaAGFpPiOUDkCBLyGrjyrdHhGSmUnsQzQ4kWPudhokbJF-k0Fcbq1ux9qv4AAVPzyJVb9OZRzyyu3d_smeE2k0zOzHKjfAYn4ir_Fi3NTW4FSrJ51xXtqBCbKzIP5juH_OTWjaIWeo-IqwXR4vnflTxbOnZExCn8n-YwIFWKdDisN80QyUcjFV0mbAiFCKE14DV8nm2acOEQx18tlMpd8jIc3kK70KlfMa-NhEaVB23gUVr1RuscVtR5Zn0EnzFRbfcZwBUoQX0kyW4HjBcTpQ8sFaRTzPAOlLXrzJiMjFVs5rMpkuejMGdy-bR4uh3IU5OFinIq_OAjsS7ye1GGjv2xPnK_IjtS9kjLv5L8vUMO_fwBUqnCTKhVs6YLfPuT-R3ht7Fk759Wq911Ts31UzpOMBCRfJp1yYWTXdupOqsAZ4gAns8Qfhdd-3xxJ7CWw6_1mDE-X23Q_qVPJU8QnmXrJEBUFa0EV4xa1SsQ7uBpuGpe5_gzIF8RTzWAR2IvMuLD-VKRva3jO7loJu7y64obAAS019lLea2cJg1uW3PccMwy7IYVk9KsxRbV82QObmw9ZdQZs8oBP_3HrZE5dwkqGRJ0Ux7CbZBYHiy2__ZEJu3aYTDLeU_3kF_TJAxYXDMZddvbi7em7ZgoaUbKDEAZDHeR-OnSXX-IVrlhclzrGfn3sEkjfx7Bcp0hy1MRps82mktmprx06ZmaYcPbIVMb7kQK0qGk4EOhE4F4HKcL93FbphwXtaPgurT93JNandRXFaWR8hgr7AfLJpoCBBlNC5PvizePgwaOZD7q6WzUdaJ_oR2QXzEU2KjhkeLCkyzssJ__ep1acnGdprA33xTtsASzHTMvuF8ObItZb9Bh7pe59ybbbkaWXUOTjBnkaKUArleIM28xj5f7E2lEr8WTiT-CcyJVaI7sWN294J1lKtVsOt3l34Kndp-4b_wLu_J9vqcA5KqVHGUm3CjH-rQrBXxCsoDH_F2W9ExJvUyiCME-kDzjBV9KQpcKPUbB4dNT_DJdt_NefM9lJsnjcPNqCRNpf3WTd8VxPM69qDnyjD7HOueQPwpBBUe4w7xJ3_aCMmMHwM0T03kELmNkfk74OVeQ6IkMDNO7sH5vFqX9rOKme5M2zficZj3xJuBlkewyzgAT1H5BbiSGXZAQ49kOu5ZvgqCPl-_iqXJrPmW_6LBbjGLIpbEYBBgELQZI-JqoEqDGhu1ejShsvYBNmtLGXHGaXgSxTpk3h_k2ojdfANI5bpHUQs8RhHi7edg2XVzWFt3LlJwUFybsrLcCWCgIXTbfAFU22aG2S16p1x_pZ4TXbZZFQVYjrMI46jMFr_--ilEm6W8sfx8WDXl5w3m5QOESk6Farp5Nm_vRFjD0eOBYh8l5S6Szs1FlNdYr9Tfd8qlZhU85IcczfIPPRgOD2HXuWP8kbNwYXQX--khlRL7EICe2D1b80DaIlaJgQlpnHcShN3xCDh9pHgN9JOFZIYDyppntmITPjLH6pdYurlf3RJX49seX1Z-lvnURNvIHqzDmz6w3qxxrfQT3lytSJGNSL9wsupmbURpvaEYl0xacsKfaPxBFux76KAy66EKJgvPlU5hTZEsuohzTDXAWfK9L_oSSpscrHct6jfE4LHWL2EFpv2MNk5R-X3-CXb4sOnTDgvg3OR5zAgbOmVbQjB9vkvzIsPZeSvgDaM6egYZ0-t7sxgDmnWaMDumbvNxeDD3AoV8258iZWG5tg1T_xH7-1fcSxWZ4ZavvD5RGYx90TqVqpA4dqU6j8XKxzJ3N9bA3ehR6W6a775ED1MA1f-1IxXjpOOBxP-PiGnvuyDlyhTZ8aL9WkGnPtkIPYTEviYzJfc5YQEAoRour_6cOcUNQRwdQ_eA7PN3Iu3Mn4Of-tL2CtexNviRYywWpg5-0FNX5mKZRB0MkeZJUobZhPS2tyjq_7Z1FgTES54tSKzXKwILUmyKHz4-A2Gc4thMvp47aij-dohi1BhmWQjVGhtyuuBeGg72wIq5xaJw1vlH_9nrc-Sz9Xnwl5NKBfR14uV3MpSL15_Ckuqg2xRCeA_N5eKeqkhF7ocW6l2Br8zITLoS2STsiWWP7_7XzaitKQq_C_KxmliQvSPOD8aEfGJcl02mql0owMNMYjDIYhDfXSdvvUzU70-r67e9_AUWokEP3IANDdVr3Jl1bEnJnGPzOFaab6r5vuqHV-wVmfQV2gmagTcemn2rttgSqV9TVTeLDLJ6Qxt-no3qswIYrh9V-G81Z5QKc86R44egxmY8AhDsQxXh40o-3OdvrlCnjs3XWAyTMVl__MZz_7TJbNfenuqoo7ZKmNHiwVllVihF7GCkgxPRQFBbj604JG3hwlCG9Baq_m0gUcVQMkXaOUtrFvxur8osY2MqziW6mAop8kj1kTUgX_KoAqWxt6e5PkoAPc5yffu_3sus9QaqW9Gw4rpqz-7-J-zNYUSrEytP56Mr_F20YE6e0nOReBCrcoIPfxCtaiUSevwRwZMFB3HOoh8TEsM_uzOvIRaoDXZPBcHUW402LKU0Ie5lyFXESfiVNTqJatU0HdwZvRtZyDLPAUGQxsAsVA1bjBUWWm2_WdcbBnBPgR-nRnqPdyoyolb5eYpibigHp029oQ4oDMxfQQBvIu4_lC6eYvw4EvEjJpqiVcy5sqYCk5bB8uipIMcuXo5rYo03dzgGG92XxxdiIST-uSIyxCTlpG3l3Lt"""
PORT_INTEL_SUMMARY_PROMPT = """gAAAAABqRJWUZuNKXOdWSGK_oeRYt2fz4AIyErq48kNUcPnQNdrhAApi1-qNjjgRnj9uYnVxd17lplZc3wrGCAuOVdpF0tEcthJ_m3y3aNvHhyyWxmzh-ejQkUWA5oqzih2f6_0lDyBN1jjbzZfODCtVlzEwM6JLnyr_9dxNt3J_0Pfp8wuqHyvxxW4lmPBdJAE1ZCstqb31eyqKEJ_aTO8UBCkLyKQfsVXHLC3szmC2XI_7a3vJ2A9m2OSNbMTK1yBZy462bLSf5G-E0AYXrihvRB4iEcTWblUhHfFt9GZhIJzXu1PrhyTck42Zk2KqJsX2mKofQ_9H25mwvGYQM613zN5QEQxtbDSxtWG3K5hF9LcQH6lDHvV22zxWQJgxmfnRUt8WL6hFhWLRN-vzwrTXRyYrX7Qxk-A_qtvrz8KBref7MCgejog="""

def get_benchmark_name(ticker):
    return BENCHMARK_NAMES.get(ticker, ticker)

#Optimistion default capital
DEFAULT_CAPITAL = 10000.0


# ============================================================
# UI Colors and Design Tokens
# ============================================================
LIGHT_ELEMENT = _NEUTRAL_0

# Text
TEXT_PRIMARY = _TEXT_PRIMARY
TEXT_SECONDARY = _TEXT_SECONDARY
TEXT_MUTED = _TEXT_MUTED
TEXT_ON_DARK = LIGHT_ELEMENT
TEXT_ON_YELLOW = _TEXT_HEADING
TEXT_TAB_HOVER = _TEXT_SECONDARY
TAB_ACTIVE = _BRAND_PRIMARY
TEXT_ERROR = _SEMANTIC_NEGATIVE_STRONG
TEXT_MARKER_DARK = _NEUTRAL_1000
TEXT_LABEL_GAUGE = _TEXT_MUTED
TEXT_HEADING_H2 = _TEXT_HEADING_H2
TEXT_HEADING_H3 = _TEXT_HEADING_H3

# Surfaces
BG_ROW_HEADER = _BG_ROW_HEADER
BG_ROW_HEADER_ALT = _BG_SUBTLE
BG_ROW_ALT = _BG_ROW_ALT_2
BG_ROW_ALT_ALT = _BG_ROW_ALT_2
BG_ROW_HOVER = _BG_ROW_HOVER
BG_CHART = _BG_CHART
BG_TAB_INACTIVE = _NEUTRAL_SURFACE
BG_TAB_HOVER = _HOVER_SURFACE
BG_ACTIVE_YELLOW = _COMMENTARY_BG
BG_OPT_CARD = _NEUTRAL_0
BG_SHOCK_KNOWLEDGE = _BG_SUBTLE
NEUTRAL_SURFACE = _NEUTRAL_SURFACE
WHITE_ELEMENT = _WHITE_ELEMENT

# Borders
BORDER_LIGHT = _BORDER_DEFAULT
BORDER_PANEL = _BORDER_DEFAULT
BORDER_CHART_HEADER = _BORDER_DEFAULT
BORDER_INFO = _SEMANTIC_NEGATIVE

SUCCESS_DARK = _SEMANTIC_POSITIVE
DANGER_DARK = _SEMANTIC_NEGATIVE
WARNING_ACCENT = _SEMANTIC_WARNING
ERR_DARK = _SEMANTIC_NEGATIVE_STRONG

# Gauges / Sliders
GAUGE_TRACK_BG = _NEUTRAL_SURFACE

# Chart series
CHART_GRID = _GRID_LINE

# Drawdown risk bar
DD_RISK_BAR_LOW = _SEMANTIC_NEGATIVE
DD_RISK_BAR_MEDIUM = _SEMANTIC_WARNING
DD_RISK_BAR_HIGH = _SEMANTIC_POSITIVE
DD_RISK_BAR_BORDER = _TEXT_PRIMARY
DD_RISK_MARKER = _NEUTRAL_1000
DD_RISK_LABEL = _TEXT_MUTED

# Correlation percentile bar
CORR_PERCENTILE_20 = _SEMANTIC_NEGATIVE
CORR_PERCENTILE_40 = _SEMANTIC_WARNING
CORR_PERCENTILE_60 = _SEMANTIC_POSITIVE
CORR_PERCENTILE_80 = _SEMANTIC_WARNING
CORR_PERCENTILE_100 = _SEMANTIC_NEGATIVE
CORR_PERCENTILE_MARKER = _NEUTRAL_1000
CORR_PERCENTILE_BORDER = _TEXT_PRIMARY

# Term curve
TERM_CARD_BORDER = _NEUTRAL_SURFACE
TERM_CARD_BAR =_BRAND_PRIMARY

# Monte Carlo card backgrounds
MC_CARD_GREEN_BORDER = _SEMANTIC_POSITIVE
MC_CARD_RED_BORDER = _SEMANTIC_NEGATIVE
MC_CARD_ORANGE_BORDER = _SEMANTIC_WARNING
MC_CARD_GRAY_BORDER = _SEMANTIC_NEUTRAL

# Stability and Regime indicator colors
STABILITY_MEDIUM = _SEMANTIC_WARNING

# Alerts / Momentum / Bias colors
ALERT_CAUTION_BG = _SEMANTIC_WARNING

# Performance pills
PILL_POSITIVE_TEXT = _SEMANTIC_POSITIVE
PILL_NEGATIVE_TEXT = _SEMANTIC_NEGATIVE
PILL_NEUTRAL_TEXT = _TEXT_MUTED

PRIMARY_TEXT = _TEXT_PRIMARY
HEADING_TEXT = _TEXT_HEADING
HEADING_TEXT_H2 = TEXT_HEADING_H2
HEADING_TEXT_H3 = TEXT_HEADING_H3
ACCENT_THEME = _BRAND_PRIMARY
SUCCESS_INDICATOR = _SEMANTIC_POSITIVE
DANGER_INDICATOR = _SEMANTIC_NEGATIVE
SUCCESS_TEXT = _SEMANTIC_POSITIVE
DANGER_TEXT = _SEMANTIC_NEGATIVE
NEUTRAL_BG = _NEUTRAL_SURFACE
NEUTRAL_TEXT = _TEXT_SECONDARY
NEUTRAL_GRAY = _SEMANTIC_NEUTRAL
BG_MAIN = _BG_DEFAULT
BORDER_THEME = _BORDER_DEFAULT
CHART_TEXT = _TEXT_MUTED
CHART_LINE_CAPITAL_GAIN = _NEUTRAL_1000
CHART_LINE_SINCE_INCEPTION = _SEMANTIC_WARNING
CHART_BENCHMARK_MARKER = _TEXT_PRIMARY

# Buttons
BG_BUTTON_PRIMARY = _TEXT_HEADING
BG_BUTTON_PRIMARY_HOVER = _SEMANTIC_NEUTRAL_HOVER
BG_BUTTON_SECONDARY = _SEMANTIC_NEUTRAL
BG_BUTTON_SECONDARY_HOVER = _SEMANTIC_NEUTRAL_STRONG
BG_BUTTON_DANGER = _SEMANTIC_NEGATIVE
BG_BUTTON_DANGER_HOVER = _SEMANTIC_NEGATIVE_STRONG
BG_BUTTON_NEUTRAL = _NEUTRAL_SURFACE
BG_BUTTON_NEUTRAL_HOVER = _HOVER_SURFACE
BUTTON_TEXT = _NEUTRAL_0

# ============================================================
# Correlation heatmap colors (charts.py)
# ============================================================
HEATMAP_NEGATIVE_CELL = _SEMANTIC_POSITIVE
HEATMAP_NEUTRAL_CELL = _NEUTRAL_0
HEATMAP_POSITIVE_CELL = _SEMANTIC_NEGATIVE
HEATMAP_DIAGONAL_CELL = _TEXT_MUTED

# Correlation distribution chart colors (correlation/charts.py)
CORR_DIST_BAR_FILL = _SEMANTIC_NEUTRAL
CORR_DIST_BAR_EDGE = _NEUTRAL_1000
CORR_DIST_MARKER_LINE = _SEMANTIC_NEGATIVE
CORR_DIST_BG = _NEUTRAL_0

# Correlation chart color helpers (correlation/charts.py)
CORR_COLOR_STRONG_POSITIVE = _SEMANTIC_POSITIVE
CORR_COLOR_MODERATE = _SEMANTIC_WARNING
CORR_COLOR_WEAK_POSITIVE = _SEMANTIC_NEUTRAL
CORR_COLOR_NEGATIVE = _SEMANTIC_NEGATIVE
CORR_COLOR_NA = _SEMANTIC_NEUTRAL

# Correlation percentile bar colors (correlation/charts.py)
CORR_PERCENTILE_EXTREME = _SEMANTIC_NEGATIVE
CORR_PERCENTILE_SOMEWHAT_EXTREME = _SEMANTIC_WARNING
CORR_PERCENTILE_NORMAL = _SEMANTIC_POSITIVE

# Correlation volatility bar colors (correlation/charts.py)
CORR_VOL_HIGH = _SEMANTIC_NEGATIVE
CORR_VOL_MODERATE = _SEMANTIC_WARNING
CORR_VOL_LOW = _SEMANTIC_POSITIVE


# ============================================================
# Overview attention table colors (overview/commentary.py)
# ============================================================
ATTENTION_TABLE_HEADER_BORDER = _BORDER_DEFAULT
ATTENTION_TABLE_CELL_BORDER = _BORDER_DEFAULT
NEGATIVE_RETURN_CELL_BG = _SEMANTIC_NEGATIVE
POSITIVE_RETURN_CELL_BG = _SEMANTIC_POSITIVE
ZERO_RETURN_CELL_BG = _BG_ROW_ALT_2
NONZERO_RETURN_CELL_TEXT = _NEUTRAL_0
ZERO_RETURN_CELL_TEXT = _TEXT_MUTED
ATTENTION_TABLE_HEADER_BG = _BG_SUBTLE
ATTENTION_TABLE_HEADER_ROW_BORDER = _BORDER_DEFAULT
TABLE_PERIOD_LABEL_TEXT = _TEXT_PRIMARY
METRIC_CARD_LABEL_TEXT = _TEXT_PRIMARY
POSITIVE_RETURN_CARD = _SEMANTIC_POSITIVE
NEGATIVE_RETURN_CARD = _SEMANTIC_NEGATIVE
UNDEFINED_METRIC_CARD = _SEMANTIC_NEUTRAL

# ============================================================
# Overview performance chart colors (overview/charts.py)
# ============================================================
PERF_BAR_POSITIVE = _SEMANTIC_POSITIVE
PERF_BAR_NEGATIVE = _SEMANTIC_NEGATIVE
PERF_ACTIVE_BUTTON_BG = _TEXT_HEADING
PERF_INACTIVE_BUTTON_BG = _SEMANTIC_NEUTRAL
DIV_YIELD_CARD_BORDER = _BRAND_PRIMARY
DIV_YIELD_CARD_TEXT = _BRAND_PRIMARY
METRIC_CARD_BORDER_SCALE = _TEXT_MUTED
BAR_OUTLINE = _TEXT_PRIMARY
BAR_VALUE_LABEL_TEXT = _TEXT_PRIMARY

# ============================================================
# Holdings table renderer colors (holdings/renderer.py)
# ============================================================
HOLDINGS_CAUTION_ALERT_BG = _SEMANTIC_NEGATIVE
HOLDINGS_ATTENTION_ALERT_BG = _SEMANTIC_WARNING
HOLDINGS_MONITOR_ALERT_BG = _SEMANTIC_POSITIVE
HOLDINGS_BULL_MOMENTUM_BG = _SEMANTIC_POSITIVE
HOLDINGS_BEAR_MOMENTUM_BG = _SEMANTIC_NEGATIVE
HOLDINGS_NEUTRAL_MOMENTUM_BG = _SEMANTIC_NEUTRAL
ZSCORE_OVERSOLD = _SEMANTIC_NEGATIVE
ZSCORE_OVERBOUGHT = _SEMANTIC_POSITIVE
ZSCORE_NEUTRAL = _SEMANTIC_NEUTRAL
UPSIDE_PRICE_TEXT = _SEMANTIC_POSITIVE
DOWNSIDE_PRICE_TEXT = _SEMANTIC_NEGATIVE
NEUTRAL_PRICE_TEXT = _SEMANTIC_NEUTRAL
NO_PRICE_COLOR = _TEXT_PRIMARY
TREND_ACCEL_BAR = _SEMANTIC_POSITIVE
TREND_DECEL_BAR = _SEMANTIC_NEGATIVE
TREND_NEUTRAL_BAR = _SEMANTIC_NEUTRAL
TREND_ACCEL_TEXT = _SEMANTIC_POSITIVE
TREND_DECEL_TEXT = _SEMANTIC_NEGATIVE
TREND_NEUTRAL_TEXT = _SEMANTIC_NEUTRAL
RSI_OVERSOLD_BG = _SEMANTIC_POSITIVE
RSI_OVERBOUGHT_BG = _SEMANTIC_NEGATIVE
HOLDINGS_EXPORT_BG = _TEXT_HEADING
HOLDINGS_TOOLTIP_BG = _TEXT_PRIMARY
HOLDINGS_HEADER_BG = _BG_ROW_HEADER
HOLDINGS_HEADER_TEXT = _TEXT_SECONDARY
HOLDINGS_CELL_BORDER = _BORDER_DEFAULT
HOLDINGS_ROW_ALT = _BG_ROW_ALT_2
HOLDINGS_HEADER_HOVER = _NEUTRAL_SURFACE
HOLDINGS_ROW_HOVER = _BG_ROW_HOVER
HOLDINGS_SORT_ARROW = _BRAND_PRIMARY
HOLDINGS_SORT_ARROW_TEXT = _TEXT_HEADING
HOLDINGS_STDEV_LABEL = _TEXT_MUTED

# Holdings commentary alert table (commentary.py)
HOLDINGS_COMMENTARY_ALERT_CAUTION = _SEMANTIC_NEGATIVE
HOLDINGS_COMMENTARY_ALERT_ATTENTION = _SEMANTIC_WARNING
HOLDINGS_COMMENTARY_ALERT_MONITOR = _SEMANTIC_POSITIVE

# ============================================================
# History chart colors (history/charts.py)
# ============================================================
EMPTY_PLACEHOLDER_TEXT = _TEXT_MUTED
TRADE_WINRATE_GOOD = _SEMANTIC_POSITIVE
TRADE_WINRATE_MODERATE = _SEMANTIC_WARNING
TRADE_WINRATE_BAD = _SEMANTIC_NEGATIVE
TRADE_RR_NEUTRAL = _SEMANTIC_NEUTRAL
TRADE_RR_GOOD = _SEMANTIC_POSITIVE
TRADE_RR_MODERATE = _SEMANTIC_WARNING
TRADE_RR_BAD = _SEMANTIC_NEGATIVE
TRADE_EXPECTANCY_GOOD = _SEMANTIC_POSITIVE
TRADE_EXPECTANCY_BAD = _SEMANTIC_NEGATIVE
TRADE_EXPECTANCY_MODERATE = _SEMANTIC_WARNING
TRADE_PF_NEUTRAL = _SEMANTIC_NEUTRAL
TRADE_PF_GOOD = _SEMANTIC_POSITIVE
TRADE_PF_MODERATE = _SEMANTIC_WARNING
TRADE_PF_BAD = _SEMANTIC_NEGATIVE
TRADE_LOSS_BAR = _SEMANTIC_NEGATIVE
TRADE_BAR_OUTLINE = _TEXT_PRIMARY
TRADE_BAR_LABEL_TEXT = _TEXT_PRIMARY
LOSS_TRADE_PIE = _HOVER_SURFACE
PIE_SLICE_BORDER = _WHITE_ELEMENT
WIN_PCT_ANNOTATION = _TEXT_MUTED

# ============================================================
# Efficiency chart colors (efficiency/charts.py)
# ============================================================
EFFICIENCY_LABEL_TEXT = _SEMANTIC_NEUTRAL_STRONG
EFFICIENCY_BETA_CARD = _BRAND_PRIMARY
EFFICIENCY_POSITIVE_CARD = _SEMANTIC_POSITIVE
EFFICIENCY_NEGATIVE_CARD = _SEMANTIC_NEGATIVE
EFFICIENCY_NEUTRAL_CARD = _SEMANTIC_NEUTRAL

# ============================================================
# Risks chart colors (risks/charts.py)
# ============================================================
RISK_NA_COLOR = _SEMANTIC_NEUTRAL
RISK_STRESS_LINE = _SEMANTIC_NEGATIVE
BENCHMARK_LINE = _TEXT_PRIMARY
RISK_DRAWDOWN_LOW = _SEMANTIC_POSITIVE
RISK_DRAWDOWN_MODERATE = _SEMANTIC_WARNING
RISK_DRAWDOWN_HIGH = _SEMANTIC_NEGATIVE
RISK_VAR_LOW = _SEMANTIC_POSITIVE
RISK_VAR_MODERATE = _SEMANTIC_WARNING
RISK_VAR_HIGH = _SEMANTIC_NEGATIVE
RISK_BETA_LOW = _SEMANTIC_POSITIVE
RISK_BETA_MARKET = _SEMANTIC_WARNING
RISK_BETA_MODERATE = _SEMANTIC_NEGATIVE
RISK_BETA_HIGH = _SEMANTIC_NEGATIVE_STRONG
VAR_CHART_MAIN_BAR = _TEXT_HEADING
VAR_CHART_TAIL_BAR = _SEMANTIC_NEGATIVE
VAR_CHART_THRESHOLD = _BRAND_PRIMARY
ES_BRACKET_LINE = _BRAND_PRIMARY

# ============================================================
# Efficiency 3D chart colors (efficiency/charts.py)
# ============================================================
EFFICIENCY_3D_GRID = _HOVER_SURFACE
EFFICIENCY_3D_ZEROLINE = _SEMANTIC_NEUTRAL
EFFICIENCY_3D_BUTTON_ACTIVE = _TEXT_HEADING
EFFICIENCY_3D_BUTTON_INACTIVE = _SEMANTIC_NEUTRAL
EFFICIENCY_SHARPE_LINE = _EFFICIENCY_SHARPE_LINE
EFFICIENCY_SORTINO_LINE = _EFFICIENCY_SORTINO_LINE
EFFICIENCY_IR_LINE = _EFFICIENCY_IR_LINE

# ============================================================
# Monte Carlo chart colors (monte_carlo/charts.py)
# ============================================================
MC_GRID = _GRID_LINE
MC_MEAN_PATH = _TEXT_PRIMARY
MC_BG = _BG_CHART
MC_POSITIVE = _SEMANTIC_POSITIVE
MC_NEGATIVE = _SEMANTIC_NEGATIVE
MC_NEUTRAL = _SEMANTIC_NEUTRAL
MC_DRAWDOWN_LOW = _SEMANTIC_POSITIVE
MC_DRAWDOWN_MODERATE = _SEMANTIC_WARNING
MC_DRAWDOWN_HIGH = _SEMANTIC_NEGATIVE

# ============================================================
# Optimisation renderer colors (optimisation/renderer.py)
# ============================================================
# Optimisation strategy constants
OPTIMISATION_CURRENT_STRATEGY = _SEMANTIC_NEUTRAL
OPTIMISATION_SHARPE_STRATEGY = _BRAND_PRIMARY
OPTIMISATION_SORTINO_STRATEGY = _SEMANTIC_POSITIVE_LIGHT
OPTIMISATION_DRAWDOWN_STRATEGY = _SEMANTIC_NEGATIVE
EFFICIENCY_SCATTER_MARKER = _BRAND_PRIMARY
EFFICIENCY_SCATTER_LINE = _SEMANTIC_NEUTRAL_HOVER
EFFICIENCY_LABEL_FONT = _TEXT_MUTED
EFFICIENCY_GRID_LINE = _GRID_LINE
EFFICIENCY_BOX_MARKER = _SEMANTIC_POSITIVE_LIGHT
EFFICIENCY_BOX_LINE = _SEMANTIC_POSITIVE

BREAKDOWN_GRID_COLOR = _GRID_LINE
BREAKDOWN_LINE_COLOR = _GRID_LINE
BREAKDOWN_NEUTRAL_ORANGE = _SEMANTIC_WARNING
BREAKDOWN_POSITIVE_GREEN = _SEMANTIC_POSITIVE
BREAKDOWN_NEGATIVE_RED = _SEMANTIC_NEGATIVE
BREAKDOWN_NEUTRAL_BLUE = _BRAND_PRIMARY

# ============================================================
# Module Visibility Toggles
# ============================================================
ENABLED_MODULES = {
    "overview": True,
    "portfolio": True,
    "stats": True,
    "holdings": True,
    "breakdown": True,
    "correlation": True,
    "monte_carlo": True,
    "risks": True,
    "efficiency": True,
    "optimisation": True,
    "history": True,
    "intel": True,
}
