# config.py
"""
Global configuration constants for the portfolio function.
"""
from Functions.themes import *

REPORT_LOGO_SRC = "https://cdn.brandfetch.io/idCL5_YhIb/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1694087448850"

ANALYSIS_PAGE_URL = "https://app.alphasentra.com/ticker/[ticker]"

# Optimisation default targets
SHARPE_TARGET = 1.0
SORTINO_TARGET = 1.5
IR_TARGET = 0.5
MAX_POSITION_SIZE = 20.0
MAX_SECTOR_SIZE = 30.0
MIN_POSITION_SIZE = 0.50

# Default market data provider
DATA_PROVIDER = "yfinance"

# Candidate benchmarks for automatic selection (ordered by preference)
BENCHMARK_CANDIDATES = ["^AXJO", "^GSPC", "^STOXX50E", "BTC-USD", "^990100-USD-STRD"]

BENCHMARK_NAMES = {
    "^AXJO": "ASX 200",
    "^GSPC": "S&P 500",
    "^STOXX50E": "Euro Stoxx 50",
    "BTC-USD": "Bitcoin",
    "^990100-USD-STRD": "MSCI World",
    "ES=F": "S&P 500 Futures",
}

# AI Prompt
PORT_INTEL_REPORT_PROMPT = """gAAAAABqQ43-8Hst3RC_2EvMq0N_dpjIPvU3LMTZiE1Lm_IqFsKwQmZaw6H66pFg7GUOZ4Kt-O1Up7WQ6daoVdHxMiq9drJu8MKyOVKKHLk765Mu32yq6FewVAVQNb72W9spCzFBDHaIKXx-I4u1d89L8EwfmL3vulBHmare402ApxK_NU87SW7teZVOzQs6SamqW3oaHOZ4jWJsQiVaImxAOztzkK-ZOw9zZQW2KuZ41uU1EAbjDjJLR3aEi2POhHuKQisEOnRoXXkpUDDzkb_z0ZGhbhIkmQomFmMSJb8C8-159Pc5FyRixZiCRJNO4H2QHVHCGh4va6P9FOe-NK5e5r7R5UuhwZHLQe2_CpY9tFH8xUXFGHRGpVh-bYPmqNerneVbnIoBcmTZpEhpOUGAZEWmTbr6t8DvLHnnFy2YjL7G-Mw0295li-S1NQdOJS-7X5_yBvSM0ZQsL4cVuxoaLUC38aOV4iWSLlzJ3XT7ufqv2UPT9pXETulsIPYeBWDMFgj8vICiI9JxZXz0jVFfQGCk-dBvOJyoM-pTyYzcTAny0-r_uNgnBlMSaftDDuIZi9ds5VlVZCQGuu-XzPQ6f8bN3VqzEuVUajyJ-ZiCnnjNGg6cp148Jv7tL6PkUoFVn9FDeiBaRUNamEW29DM0Ii3hzjYL2OxpjfVVwrveUKDrT28O-dKYQKwjp8XX5lbP9B-IgpOKWo-w5YFwWsVFOcFI5-btmjza6krbqknNFy6JCM3EVxzm3INLaezdRAO5RG-GKvJJMCWfuvxP7zPDD5hzbw9dH3gqT7i4IxUtyCp0BFNYiiZi8I1dYJExitR77Wp1ZwOj3Q4EW7ykAnIq1HctDW5LJO-AMSzKfEgfOVyet3sXsz4AI8z5miH23I3ZCQ18kr0mGG7rvBVx-ITbs-de7m-bRY4kRym9X-KVTss89yWxP4xQqnU2ivHwENgnELYVZQLm4gBCd-EI0nhArUDrZmZuNjqahDmWC9dnHmoPIKWz_pY3SASEzCLmNEjRcBp-S8x07xdYbSLp-T5yKWdvuX-hjCIuKjBW9KObKJzSO2zsuhqfKINF9QTeVU58cvBd9dgP7OcgL4lFfPav9k0onBPSMmxnNDYLk1sBmWrfBl4gXGxWzfA9y_vMlk9mTgO43lg_bpStrFbmK_FhKUp-QekO6ALvy2JXxE33Q_DkoStM15AQ9fNFof3ZH0FPIw5sQs4bVzKlkJyyp-gteOX5An8aSiFHbRqEpypgOGyfNU8zdvL6HD5gYfUOQ1IOGx5eYkdMvPXa5dV2GSE0TmIHPS2vmNYWyjWonUJyEMbqM2xR8Vl7SFNmjFOkApsISzw9U4oXgXjO77lwa954iJHdqhh83IkrU8MTJdD0dpfdn9vOHDeafAgAoaa7YlZk0CyvKu5XEATXEf6BLcDfnmFZoV7lC01LYlRX5fFFr7j6WSg2L9_VtNW8e1to9olNwh94fAMogWrPtTZy0kVjREsJRWAmbvUB4kOrzAxbUo4eCJtRenoMzBsgwl1fp6Z1ZtwfoLfu6vZFRZ5tUXUHLDG_hbJXoX5O1W9jpcYbjawTeQZoamTCydLm-UWwxfhOKbJ2gBT7aTjGz8AjLySdOE_qvWzneq_I5TZWao3sqQQTTrc9ScNwIng3Aq-fY7WQ86nV6K5xTwp_6kRLC4bciHb4gsDHNuXnVWkCzCqcdG16FSbQsElYe9clZgZ-_3uHXbuJZULJeUdqtr48GgOonqafDc4oue8rxg1U6ntCyl5c0OIZ6H72SFDY_N2IiqHyb6dmmCGjc2P366T8IcqDOe002EKmhdRnPo5Qu4Fx262ZeYfl3eu8nP-YpOn3H5o3g8VHAl3kb7MNQhfyq0SQMWB8AQB3RgI-ProhymR9B0RxVXmh1TFT2Y4ID8lhN-ZYX1PQJiBDg-V8hlYSKKeANZhazjjks5nNJ0p2p7N1j5tqXIxhJQbgryFLacVSAhE7tDuCI_cErLUr8u6QtVEJTo7L_KgQmG2WBCvV7qLhs3d-aNCVwLPKvvxFhvibf-mvLWv9o4HeZ_5SqHDLxbRG5KOalDki_Js43Jg8GWtpvI_IG8qeB5ihcjcXbNWwBq6ayl6Nd2bOGKqjaxr36dBU3NKITwIKetg1lRgLlkNbwzXLWrM3mGy6wd084ldvoyxv5o6ikDG2cRfS0Tw4ZmrXpuzclM_Wxym0TzWENTpmq0KOjU08YbT7OvCJZs32mnqLp7qx53UJJz3iKnnrk3_r7Y8yA6cHpE6keAsZyvjHgWspie1Qj9w-xG1pF3oLRYgCLCp6RZVDlnp57__FNijPTFL0d3809Os_bO2DSvevW4tVfVij47Gq-mEUc9tKbfKiCWhbhY6AvBs3T-OXEze8cb_WcovIJjRNuK92hh_yJp0bpfaVU565_NK05Nt4zd_qlHHseJcle6G32Kzku6Wbip15ts2gpwjrKWPt-BVPl9QssLNx-6axi7oniVvPeylAq7lqz_zgLtevJjOjYvaooC_rCE7ePiNgLgG1pVDj6vy3KSqbt6lOazzjCOoUWe9cX1Pz2uT7K-09rj123Bn-AEQuIYZgRaP1wY12wY9vHhXMbGP87wWFk4rbPaZ3YqHqvW6Aa80Dh9YVfi4_yMtfEdclXd3dNvBpG-9m-TEPSvyApMdCsBE5EBMcDDsqcr0pMdyLCbeS05yFXy2G0UgnP57vEMnVnVBkyEozwSuzRlfLX694vy06zcLhnnB6zNc83_skIDXz80rzZBjA7jKc1Ik1vhNxroQG1Cd_27sINp2FWkVHexNiXYGsCI298k8ZC0oKqENnRVYgnF3MS7BhUX6V_4pjaQteps__SjFub2aopqnusM-WkbcihGeWH3MAedkmfkKQ03VZJ5kJy58LVzi_XDeuzTCsrSkXOorM2Y9ak5IZFlp2-o_hVKF0pbrMOQGGUJX3y8kVshndRKG3pj-c6Eaj58wXF9OAqr1exb92XWDKlzMM72vJgMCi4oOl6qjvcv2SZtjXxYzFO_I-_sugKsG8hreCX_58vrmsAT6xoj6F9vrYlmyx8Jp8oSi6-n8Vh4uesShLx-HDskusqWgdxsTPMc8KlDI67PyaQLwtwNQUKYssHN1fKbAlq3de6xqGBFSnP5phql-pwXk3nbm0zkuK9Aj7joQKRmSWC7Zovae4DuwXjKVhwLPhGyBvgav9_OyL9QcF7MMWIVpmIjrpqgxar1N_HJVOBNTV8XVcZBknw-_5-2tNGz7FVinQJConuBkN0DbIU34qA2MUbGr6RS-UQFC8L1StOFbwLcqLTkXtJAl5AEAPiaOyyjwvGNb9ZmlRSvef8hNk73l8xQyLIPXkzFnh_IWUAFhekvSkRA6Fio5Nz76blpn_idCz2slfmxNTEbN_zQTyepduOaF5V-ryi9HIdk3ovmwmIjAKZHgcBwVdFaRsDtYCtiRMBDpG-SB37SBKg85ATveard7WeuCvMKe_pHTxBg-za7hPOD3igKEZtGT-bELS2XsEnfdVCJcmhf5Szv6NvpfWJ9cKDkPjp5QN-qFGUghebP37-avJBu1q_Hd3HnXcWr2dxbZEDysZV9YR5T-tQya5mZ-qWJi2VIO1saPXQVEreHREvMGUvnP3nRlHdySG21HtSL6jlJLH8bOTBBe-fmhBUe98cXapHE3fYXwCb8_J3P8ZB9VLEvXdhUMISgcFqs484I0_mYYCxfV1Yr_V_iNHAmV2uEoQE24aYJp7_6GPVzq5MRb6kJNss2eQSSuxqxYXg5hz5sTZhZFv5wlgOFNkP_b_BNlUIhAqGNcy2u_M80SojZO6Eu49WJBEErwmcg7YTcXV7iLRg91k0bBdKY26X1Wd_7NfH5YcYamw1IgCbSXzhS-iLqWw1jaVix7hszDFncpmSc5OW1zY4QMQuZtKGowHVHzZCkj2wzHbnrqQTDUbwBdeY1Pw0PBE-2SjfHJaOiI4IFaK6mF-_f0F7QwyJStjqwBnrEjjgZ6Ze79nENJiV1ijv2GNrzKfNLrLRIWJr38i7H-nCQJYX7w-jhFQsPAkDx9Douu3uq6KHTOlhCBVDylrvZ-xCIdnGePCVU5nnc8z32bCdQeCe_22IEBZ2-qYnPClbkhFxwWi4qXSNqhIUrlUEDgaOTUYJJIPqCShKZP3kqzQ9L-OSFvgOFUlFE5igUdEGTzUHCUXBw92bdJmhjbpXWw10_fAQ0Fr3YnCHJG7qb-k9R-VcxdtLQuJnFE0HGDA9Ca5W2e6eeL0fYfBhaDwhW7Uakx1HxzvSbL1A7I7ThlkIMnnNpwqcZSsUYHQapLiSNRvl9FHgOe0c-CxYN5Ju2WSulHJ_ANua6OXih8bZ2PaoSEGWMl7eMsHlLewATgdYeXV6a-epW1R54PKgIPWMqaFVyzg-ear0ua7UrxIDMAv9ue9x1Dgo8UX4C_DMNLVWoot27Uy1KBUk2tc-ur9WHR2ynu09AlLFkigJB9ONIz7rsDBbiwy5uXdL3aQDA3v3P60j3hjvI504RoRoV9VCtT80bVvak3cQJCAkdco_ys9SPW-ryCgtgbiso5kA4XxUGrbqcbIV0n1zoYSzrrSXutTy3HhYZGT7uBdIcJVxtJXk7LiQcyBZr51j-ERt4Z6HtEUD0aom1Frra-HPV_bjt5n1PlgIs0R8pafwpJMZjNn"""

def get_benchmark_name(ticker):
    return BENCHMARK_NAMES.get(ticker, ticker)

#Optimistion default capital
DEFAULT_CAPITAL = 10000.0


# ============================================================
# UI Colors and Design Tokens
# ============================================================
LIGHT_ELEMENT = _NEUTRAL_0

# Text
TEXT_PRIMARY = _TEXT_PRIMARY
TEXT_SECONDARY = _TEXT_SECONDARY
TEXT_MUTED = _TEXT_MUTED
TEXT_ON_DARK = LIGHT_ELEMENT
TEXT_ON_YELLOW = _TEXT_HEADING
TEXT_TAB_HOVER = _TEXT_SECONDARY
TAB_ACTIVE = _BRAND_PRIMARY
TEXT_ERROR = _SEMANTIC_NEGATIVE_STRONG
TEXT_MARKER_DARK = _NEUTRAL_1000
TEXT_LABEL_GAUGE = _TEXT_MUTED
TEXT_HEADING_H2 = _TEXT_HEADING_H2
TEXT_HEADING_H3 = _TEXT_HEADING_H3

# Surfaces
BG_ROW_HEADER = _BG_ROW_HEADER
BG_ROW_HEADER_ALT = _BG_SUBTLE
BG_ROW_ALT = _BG_ROW_ALT_2
BG_ROW_ALT_ALT = _BG_ROW_ALT_2
BG_ROW_HOVER = _BG_ROW_HOVER
BG_CHART = _BG_CHART
BG_TAB_INACTIVE = _NEUTRAL_SURFACE
BG_TAB_HOVER = _HOVER_SURFACE
BG_ACTIVE_YELLOW = _COMMENTARY_BG
BG_OPT_CARD = _NEUTRAL_0
BG_SHOCK_KNOWLEDGE = _BG_SUBTLE
NEUTRAL_SURFACE = _NEUTRAL_SURFACE
WHITE_ELEMENT = _WHITE_ELEMENT

# Borders
BORDER_LIGHT = _BORDER_DEFAULT
BORDER_PANEL = _BORDER_DEFAULT
BORDER_CHART_HEADER = _BORDER_DEFAULT
BORDER_INFO = _SEMANTIC_NEGATIVE

SUCCESS_DARK = _SEMANTIC_POSITIVE
DANGER_DARK = _SEMANTIC_NEGATIVE
WARNING_ACCENT = _SEMANTIC_WARNING
ERR_DARK = _SEMANTIC_NEGATIVE_STRONG

# Gauges / Sliders
GAUGE_TRACK_BG = _NEUTRAL_SURFACE

# Chart series
CHART_GRID = _GRID_LINE

# Drawdown risk bar
DD_RISK_BAR_LOW = _SEMANTIC_NEGATIVE
DD_RISK_BAR_MEDIUM = _SEMANTIC_WARNING
DD_RISK_BAR_HIGH = _SEMANTIC_POSITIVE
DD_RISK_BAR_BORDER = _TEXT_PRIMARY
DD_RISK_MARKER = _NEUTRAL_1000
DD_RISK_LABEL = _TEXT_MUTED

# Correlation percentile bar
CORR_PERCENTILE_20 = _SEMANTIC_NEGATIVE
CORR_PERCENTILE_40 = _SEMANTIC_WARNING
CORR_PERCENTILE_60 = _SEMANTIC_POSITIVE
CORR_PERCENTILE_80 = _SEMANTIC_WARNING
CORR_PERCENTILE_100 = _SEMANTIC_NEGATIVE
CORR_PERCENTILE_MARKER = _NEUTRAL_1000
CORR_PERCENTILE_BORDER = _TEXT_PRIMARY

# Term curve
TERM_CARD_BORDER = _NEUTRAL_SURFACE
TERM_CARD_BAR =_BRAND_PRIMARY

# Monte Carlo card backgrounds
MC_CARD_GREEN_BORDER = _SEMANTIC_POSITIVE
MC_CARD_RED_BORDER = _SEMANTIC_NEGATIVE
MC_CARD_ORANGE_BORDER = _SEMANTIC_WARNING
MC_CARD_GRAY_BORDER = _SEMANTIC_NEUTRAL

# Stability and Regime indicator colors
STABILITY_MEDIUM = _SEMANTIC_WARNING

# Alerts / Momentum / Bias colors
ALERT_CAUTION_BG = _SEMANTIC_WARNING

# Performance pills
PILL_POSITIVE_TEXT = _SEMANTIC_POSITIVE
PILL_NEGATIVE_TEXT = _SEMANTIC_NEGATIVE
PILL_NEUTRAL_TEXT = _TEXT_MUTED

PRIMARY_TEXT = _TEXT_PRIMARY
HEADING_TEXT = _TEXT_HEADING
HEADING_TEXT_H2 = TEXT_HEADING_H2
HEADING_TEXT_H3 = TEXT_HEADING_H3
ACCENT_THEME = _BRAND_PRIMARY
SUCCESS_INDICATOR = _SEMANTIC_POSITIVE
DANGER_INDICATOR = _SEMANTIC_NEGATIVE
SUCCESS_TEXT = _SEMANTIC_POSITIVE
DANGER_TEXT = _SEMANTIC_NEGATIVE
NEUTRAL_BG = _NEUTRAL_SURFACE
NEUTRAL_TEXT = _TEXT_SECONDARY
NEUTRAL_GRAY = _SEMANTIC_NEUTRAL
BG_MAIN = _BG_DEFAULT
BORDER_THEME = _BORDER_DEFAULT
CHART_TEXT = _TEXT_MUTED
CHART_LINE_CAPITAL_GAIN = _NEUTRAL_1000
CHART_LINE_SINCE_INCEPTION = _SEMANTIC_WARNING
CHART_BENCHMARK_MARKER = _TEXT_PRIMARY

# Buttons
BG_BUTTON_PRIMARY = _TEXT_HEADING
BG_BUTTON_PRIMARY_HOVER = _SEMANTIC_NEUTRAL_HOVER
BG_BUTTON_SECONDARY = _SEMANTIC_NEUTRAL
BG_BUTTON_SECONDARY_HOVER = _SEMANTIC_NEUTRAL_STRONG
BG_BUTTON_DANGER = _SEMANTIC_NEGATIVE
BG_BUTTON_DANGER_HOVER = _SEMANTIC_NEGATIVE_STRONG
BG_BUTTON_NEUTRAL = _NEUTRAL_SURFACE
BG_BUTTON_NEUTRAL_HOVER = _HOVER_SURFACE
BUTTON_TEXT = _NEUTRAL_0

# ============================================================
# Correlation heatmap colors (charts.py)
# ============================================================
HEATMAP_NEGATIVE_CELL = _SEMANTIC_POSITIVE
HEATMAP_NEUTRAL_CELL = _NEUTRAL_0
HEATMAP_POSITIVE_CELL = _SEMANTIC_NEGATIVE
HEATMAP_DIAGONAL_CELL = _TEXT_MUTED

# Correlation distribution chart colors (correlation/charts.py)
CORR_DIST_BAR_FILL = _SEMANTIC_NEUTRAL
CORR_DIST_BAR_EDGE = _NEUTRAL_1000
CORR_DIST_MARKER_LINE = _SEMANTIC_NEGATIVE
CORR_DIST_BG = _NEUTRAL_0

# Correlation chart color helpers (correlation/charts.py)
CORR_COLOR_STRONG_POSITIVE = _SEMANTIC_POSITIVE
CORR_COLOR_MODERATE = _SEMANTIC_WARNING
CORR_COLOR_WEAK_POSITIVE = _SEMANTIC_NEUTRAL
CORR_COLOR_NEGATIVE = _SEMANTIC_NEGATIVE
CORR_COLOR_NA = _SEMANTIC_NEUTRAL

# Correlation percentile bar colors (correlation/charts.py)
CORR_PERCENTILE_EXTREME = _SEMANTIC_NEGATIVE
CORR_PERCENTILE_SOMEWHAT_EXTREME = _SEMANTIC_WARNING
CORR_PERCENTILE_NORMAL = _SEMANTIC_POSITIVE

# Correlation volatility bar colors (correlation/charts.py)
CORR_VOL_HIGH = _SEMANTIC_NEGATIVE
CORR_VOL_MODERATE = _SEMANTIC_WARNING
CORR_VOL_LOW = _SEMANTIC_POSITIVE


# ============================================================
# Overview attention table colors (overview/commentary.py)
# ============================================================
ATTENTION_TABLE_HEADER_BORDER = _BORDER_DEFAULT
ATTENTION_TABLE_CELL_BORDER = _BORDER_DEFAULT
NEGATIVE_RETURN_CELL_BG = _SEMANTIC_NEGATIVE
POSITIVE_RETURN_CELL_BG = _SEMANTIC_POSITIVE
ZERO_RETURN_CELL_BG = _BG_ROW_ALT_2
NONZERO_RETURN_CELL_TEXT = _NEUTRAL_0
ZERO_RETURN_CELL_TEXT = _TEXT_MUTED
ATTENTION_TABLE_HEADER_BG = _BG_SUBTLE
ATTENTION_TABLE_HEADER_ROW_BORDER = _BORDER_DEFAULT
TABLE_PERIOD_LABEL_TEXT = _TEXT_PRIMARY
METRIC_CARD_LABEL_TEXT = _TEXT_PRIMARY
POSITIVE_RETURN_CARD = _SEMANTIC_POSITIVE
NEGATIVE_RETURN_CARD = _SEMANTIC_NEGATIVE
UNDEFINED_METRIC_CARD = _SEMANTIC_NEUTRAL

# ============================================================
# Overview performance chart colors (overview/charts.py)
# ============================================================
PERF_BAR_POSITIVE = _SEMANTIC_POSITIVE
PERF_BAR_NEGATIVE = _SEMANTIC_NEGATIVE
PERF_ACTIVE_BUTTON_BG = _TEXT_HEADING
PERF_INACTIVE_BUTTON_BG = _SEMANTIC_NEUTRAL
DIV_YIELD_CARD_BORDER = _BRAND_PRIMARY
DIV_YIELD_CARD_TEXT = _BRAND_PRIMARY
METRIC_CARD_BORDER_SCALE = _TEXT_MUTED
BAR_OUTLINE = _TEXT_PRIMARY
BAR_VALUE_LABEL_TEXT = _TEXT_PRIMARY

# ============================================================
# Holdings table renderer colors (holdings/renderer.py)
# ============================================================
HOLDINGS_CAUTION_ALERT_BG = _SEMANTIC_NEGATIVE
HOLDINGS_ATTENTION_ALERT_BG = _SEMANTIC_WARNING
HOLDINGS_MONITOR_ALERT_BG = _SEMANTIC_POSITIVE
HOLDINGS_BULL_MOMENTUM_BG = _SEMANTIC_POSITIVE
HOLDINGS_BEAR_MOMENTUM_BG = _SEMANTIC_NEGATIVE
HOLDINGS_NEUTRAL_MOMENTUM_BG = _SEMANTIC_NEUTRAL
ZSCORE_OVERSOLD = _SEMANTIC_NEGATIVE
ZSCORE_OVERBOUGHT = _SEMANTIC_POSITIVE
ZSCORE_NEUTRAL = _SEMANTIC_NEUTRAL
UPSIDE_PRICE_TEXT = _SEMANTIC_POSITIVE
DOWNSIDE_PRICE_TEXT = _SEMANTIC_NEGATIVE
NEUTRAL_PRICE_TEXT = _SEMANTIC_NEUTRAL
NO_PRICE_COLOR = _TEXT_PRIMARY
TREND_ACCEL_BAR = _SEMANTIC_POSITIVE
TREND_DECEL_BAR = _SEMANTIC_NEGATIVE
TREND_NEUTRAL_BAR = _SEMANTIC_NEUTRAL
TREND_ACCEL_TEXT = _SEMANTIC_POSITIVE
TREND_DECEL_TEXT = _SEMANTIC_NEGATIVE
TREND_NEUTRAL_TEXT = _SEMANTIC_NEUTRAL
RSI_OVERSOLD_BG = _SEMANTIC_POSITIVE
RSI_OVERBOUGHT_BG = _SEMANTIC_NEGATIVE
HOLDINGS_EXPORT_BG = _TEXT_HEADING
HOLDINGS_TOOLTIP_BG = _TEXT_PRIMARY
HOLDINGS_HEADER_BG = _BG_ROW_HEADER
HOLDINGS_HEADER_TEXT = _TEXT_SECONDARY
HOLDINGS_CELL_BORDER = _BORDER_DEFAULT
HOLDINGS_ROW_ALT = _BG_ROW_ALT_2
HOLDINGS_HEADER_HOVER = _NEUTRAL_SURFACE
HOLDINGS_ROW_HOVER = _BG_ROW_HOVER
HOLDINGS_SORT_ARROW = _BRAND_PRIMARY
HOLDINGS_SORT_ARROW_TEXT = _TEXT_HEADING
HOLDINGS_STDEV_LABEL = _TEXT_MUTED

# Holdings commentary alert table (commentary.py)
HOLDINGS_COMMENTARY_ALERT_CAUTION = _SEMANTIC_NEGATIVE
HOLDINGS_COMMENTARY_ALERT_ATTENTION = _SEMANTIC_WARNING
HOLDINGS_COMMENTARY_ALERT_MONITOR = _SEMANTIC_POSITIVE

# ============================================================
# History chart colors (history/charts.py)
# ============================================================
EMPTY_PLACEHOLDER_TEXT = _TEXT_MUTED
TRADE_WINRATE_GOOD = _SEMANTIC_POSITIVE
TRADE_WINRATE_MODERATE = _SEMANTIC_WARNING
TRADE_WINRATE_BAD = _SEMANTIC_NEGATIVE
TRADE_RR_NEUTRAL = _SEMANTIC_NEUTRAL
TRADE_RR_GOOD = _SEMANTIC_POSITIVE
TRADE_RR_MODERATE = _SEMANTIC_WARNING
TRADE_RR_BAD = _SEMANTIC_NEGATIVE
TRADE_EXPECTANCY_GOOD = _SEMANTIC_POSITIVE
TRADE_EXPECTANCY_BAD = _SEMANTIC_NEGATIVE
TRADE_EXPECTANCY_MODERATE = _SEMANTIC_WARNING
TRADE_PF_NEUTRAL = _SEMANTIC_NEUTRAL
TRADE_PF_GOOD = _SEMANTIC_POSITIVE
TRADE_PF_MODERATE = _SEMANTIC_WARNING
TRADE_PF_BAD = _SEMANTIC_NEGATIVE
TRADE_LOSS_BAR = _SEMANTIC_NEGATIVE
TRADE_BAR_OUTLINE = _TEXT_PRIMARY
TRADE_BAR_LABEL_TEXT = _TEXT_PRIMARY
LOSS_TRADE_PIE = _HOVER_SURFACE
PIE_SLICE_BORDER = _WHITE_ELEMENT
WIN_PCT_ANNOTATION = _TEXT_MUTED

# ============================================================
# Efficiency chart colors (efficiency/charts.py)
# ============================================================
EFFICIENCY_LABEL_TEXT = _SEMANTIC_NEUTRAL_STRONG
EFFICIENCY_BETA_CARD = _BRAND_PRIMARY
EFFICIENCY_POSITIVE_CARD = _SEMANTIC_POSITIVE
EFFICIENCY_NEGATIVE_CARD = _SEMANTIC_NEGATIVE
EFFICIENCY_NEUTRAL_CARD = _SEMANTIC_NEUTRAL

# ============================================================
# Risks chart colors (risks/charts.py)
# ============================================================
RISK_NA_COLOR = _SEMANTIC_NEUTRAL
RISK_STRESS_LINE = _SEMANTIC_NEGATIVE
BENCHMARK_LINE = _TEXT_PRIMARY
RISK_DRAWDOWN_LOW = _SEMANTIC_POSITIVE
RISK_DRAWDOWN_MODERATE = _SEMANTIC_WARNING
RISK_DRAWDOWN_HIGH = _SEMANTIC_NEGATIVE
RISK_VAR_LOW = _SEMANTIC_POSITIVE
RISK_VAR_MODERATE = _SEMANTIC_WARNING
RISK_VAR_HIGH = _SEMANTIC_NEGATIVE
RISK_BETA_LOW = _SEMANTIC_POSITIVE
RISK_BETA_MARKET = _SEMANTIC_WARNING
RISK_BETA_MODERATE = _SEMANTIC_NEGATIVE
RISK_BETA_HIGH = _SEMANTIC_NEGATIVE_STRONG
VAR_CHART_MAIN_BAR = _TEXT_HEADING
VAR_CHART_TAIL_BAR = _SEMANTIC_NEGATIVE
VAR_CHART_THRESHOLD = _BRAND_PRIMARY
ES_BRACKET_LINE = _BRAND_PRIMARY

# ============================================================
# Efficiency 3D chart colors (efficiency/charts.py)
# ============================================================
EFFICIENCY_3D_GRID = _HOVER_SURFACE
EFFICIENCY_3D_ZEROLINE = _SEMANTIC_NEUTRAL
EFFICIENCY_3D_BUTTON_ACTIVE = _TEXT_HEADING
EFFICIENCY_3D_BUTTON_INACTIVE = _SEMANTIC_NEUTRAL
EFFICIENCY_SHARPE_LINE = _EFFICIENCY_SHARPE_LINE
EFFICIENCY_SORTINO_LINE = _EFFICIENCY_SORTINO_LINE
EFFICIENCY_IR_LINE = _EFFICIENCY_IR_LINE

# ============================================================
# Monte Carlo chart colors (monte_carlo/charts.py)
# ============================================================
MC_GRID = _GRID_LINE
MC_MEAN_PATH = _TEXT_PRIMARY
MC_BG = _BG_CHART
MC_POSITIVE = _SEMANTIC_POSITIVE
MC_NEGATIVE = _SEMANTIC_NEGATIVE
MC_NEUTRAL = _SEMANTIC_NEUTRAL
MC_DRAWDOWN_LOW = _SEMANTIC_POSITIVE
MC_DRAWDOWN_MODERATE = _SEMANTIC_WARNING
MC_DRAWDOWN_HIGH = _SEMANTIC_NEGATIVE

# ============================================================
# Optimisation renderer colors (optimisation/renderer.py)
# ============================================================
# Optimisation strategy constants
OPTIMISATION_CURRENT_STRATEGY = _SEMANTIC_NEUTRAL
OPTIMISATION_SHARPE_STRATEGY = _BRAND_PRIMARY
OPTIMISATION_SORTINO_STRATEGY = _SEMANTIC_POSITIVE_LIGHT
OPTIMISATION_DRAWDOWN_STRATEGY = _SEMANTIC_NEGATIVE
EFFICIENCY_SCATTER_MARKER = _BRAND_PRIMARY
EFFICIENCY_SCATTER_LINE = _SEMANTIC_NEUTRAL_HOVER
EFFICIENCY_LABEL_FONT = _TEXT_MUTED
EFFICIENCY_GRID_LINE = _GRID_LINE
EFFICIENCY_BOX_MARKER = _SEMANTIC_POSITIVE_LIGHT
EFFICIENCY_BOX_LINE = _SEMANTIC_POSITIVE

BREAKDOWN_GRID_COLOR = _GRID_LINE
BREAKDOWN_LINE_COLOR = _GRID_LINE
BREAKDOWN_NEUTRAL_ORANGE = _SEMANTIC_WARNING
BREAKDOWN_POSITIVE_GREEN = _SEMANTIC_POSITIVE
BREAKDOWN_NEGATIVE_RED = _SEMANTIC_NEGATIVE
BREAKDOWN_NEUTRAL_BLUE = _BRAND_PRIMARY

# ============================================================
# Module Visibility Toggles
# ============================================================
ENABLED_MODULES = {
    "overview": True,
    "portfolio": True,
    "stats": True,
    "holdings": True,
    "breakdown": True,
    "correlation": True,
    "monte_carlo": True,
    "risks": True,
    "efficiency": True,
    "optimisation": True,
    "history": True,
    "intel": True,
}
